[project]
name = "gestmat"
version = "0.1.0"
description = "Experimental framework"
requires-python = ">=3.10"
dependencies = []
license = {text = "MIT OR Apache-2.0"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
