import {
  ADMIN_ROLE,
  REGISSEUR_GENERAL_ROLE,
  REGISSEUR_LUMIERE_ROLE,
  REGISSEUR_SON_ROLE,
  REGISSEUR_PLATEAU_ROLE,
  AUTRE_ROLE,
} from './roles';

export type PermissionRule = {
  roles: string[];
  structureScoped?: boolean;
  usageTypes?: string[];
};

export const VEHICLE_USAGE_TYPES = ['technique', 'logistique'];

export const PERMISSIONS: Record<string, PermissionRule | string[]> = {
  MANAGE_STRUCTURES: [ADMIN_ROLE],
  MANAGE_USERS: [ADMIN_ROLE],
  MANAGE_STATS: [ADMIN_ROLE],
  MANAGE_LOANS: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
    AUTRE_ROLE,
  ],
  MANAGE_EQUIPMENTS: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
  ],
  VEHICLES_CREATE: {
    roles: [
      REGISSEUR_GENERAL_ROLE,
      REGISSEUR_LUMIERE_ROLE,
      REGISSEUR_SON_ROLE,
      REGISSEUR_PLATEAU_ROLE,
      ADMIN_ROLE,
    ],
    usageTypes: VEHICLE_USAGE_TYPES,
  },
  VEHICLES_UPDATE: {
    roles: [
      REGISSEUR_GENERAL_ROLE,
      REGISSEUR_LUMIERE_ROLE,
      REGISSEUR_SON_ROLE,
      REGISSEUR_PLATEAU_ROLE,
      ADMIN_ROLE,
    ],
    structureScoped: true,
  },
  VEHICLES_ASSIGN: {
    roles: [REGISSEUR_GENERAL_ROLE, ADMIN_ROLE],
    structureScoped: true,
    usageTypes: VEHICLE_USAGE_TYPES,
  },
  VEHICLES_ARCHIVE: {
    roles: [REGISSEUR_GENERAL_ROLE, ADMIN_ROLE],
    structureScoped: true,
  },
  MANAGE_INVESTMENTS: {
    roles: [REGISSEUR_GENERAL_ROLE, ADMIN_ROLE],
    structureScoped: true,
  },
};

export const MANAGE_STRUCTURES = 'MANAGE_STRUCTURES';
export const MANAGE_USERS = 'MANAGE_USERS';
export const MANAGE_STATS = 'MANAGE_STATS';
export const MANAGE_LOANS = 'MANAGE_LOANS';
export const MANAGE_EQUIPMENTS = 'MANAGE_EQUIPMENTS';
export const VEHICLES_CREATE = 'VEHICLES_CREATE';
export const VEHICLES_UPDATE = 'VEHICLES_UPDATE';
export const VEHICLES_ASSIGN = 'VEHICLES_ASSIGN';
export const VEHICLES_ARCHIVE = 'VEHICLES_ARCHIVE';
export const MANAGE_INVESTMENTS = 'MANAGE_INVESTMENTS';

export default {
  PERMISSIONS,
  MANAGE_STRUCTURES,
  MANAGE_USERS,
  MANAGE_STATS,
  MANAGE_LOANS,
  MANAGE_EQUIPMENTS,
  VEHICLES_CREATE,
  VEHICLES_UPDATE,
  VEHICLES_ASSIGN,
  VEHICLES_ARCHIVE,
  MANAGE_INVESTMENTS,
};
