const {
  ADMIN_ROLE,
  EQUIPMENT_MANAGER_ROLE,
  LOAN_MANAGER_ROLE,
  USER_MANAGER_ROLE,
  STRUCTURE_MANAGER_ROLE,
} = require('./roles');

const PERMISSIONS = {
  MANAGE_STRUCTURES: [ADMIN_ROLE, STRUCTURE_MANAGER_ROLE],
  MANAGE_USERS: [ADMIN_ROLE, USER_MANAGER_ROLE],
  MANAGE_LOANS: [ADMIN_ROLE, LOAN_MANAGER_ROLE],
  MANAGE_EQUIPMENTS: [ADMIN_ROLE, EQUIPMENT_MANAGER_ROLE],
};

module.exports = {
  PERMISSIONS,
  MANAGE_STRUCTURES: 'MANAGE_STRUCTURES',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_LOANS: 'MANAGE_LOANS',
  MANAGE_EQUIPMENTS: 'MANAGE_EQUIPMENTS',
};
