import {
  ADMIN_ROLE,
  REGISSEUR_GENERAL_ROLE,
  REGISSEUR_LUMIERE_ROLE,
  REGISSEUR_SON_ROLE,
  REGISSEUR_PLATEAU_ROLE,
  AUTRE_ROLE,
} from './roles';

export const PERMISSIONS = {
  MANAGE_STRUCTURES: [ADMIN_ROLE],
  MANAGE_USERS: [ADMIN_ROLE],
  MANAGE_STATS: [ADMIN_ROLE],
  MANAGE_LOANS: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
    AUTRE_ROLE,
  ],
  MANAGE_EQUIPMENTS: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
  ],
  MANAGE_VEHICLES: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
  ],
};

export const MANAGE_STRUCTURES = 'MANAGE_STRUCTURES';
export const MANAGE_USERS = 'MANAGE_USERS';
export const MANAGE_STATS = 'MANAGE_STATS';
export const MANAGE_LOANS = 'MANAGE_LOANS';
export const MANAGE_EQUIPMENTS = 'MANAGE_EQUIPMENTS';
export const MANAGE_VEHICLES = 'MANAGE_VEHICLES';

export default {
  PERMISSIONS,
  MANAGE_STRUCTURES,
  MANAGE_USERS,
  MANAGE_STATS,
  MANAGE_LOANS,
  MANAGE_EQUIPMENTS,
  MANAGE_VEHICLES,
};
