const {
  ADMIN_ROLE,
  REGISSEUR_GENERAL_ROLE,
  REGISSEUR_LUMIERE_ROLE,
  REGISSEUR_SON_ROLE,
  REGISSEUR_PLATEAU_ROLE,
  AUTRE_ROLE,
} = require('./roles');

const PERMISSIONS = {
  MANAGE_STRUCTURES: [ADMIN_ROLE],
  MANAGE_USERS: [ADMIN_ROLE],
  MANAGE_STATS: [ADMIN_ROLE],
  MANAGE_LOANS: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
    AUTRE_ROLE,
  ],
  MANAGE_EQUIPMENTS: [
    REGISSEUR_GENERAL_ROLE,
    REGISSEUR_LUMIERE_ROLE,
    REGISSEUR_SON_ROLE,
    REGISSEUR_PLATEAU_ROLE,
    ADMIN_ROLE,
  ],
};

module.exports = {
  PERMISSIONS,
  MANAGE_STRUCTURES: 'MANAGE_STRUCTURES',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_STATS: 'MANAGE_STATS',
  MANAGE_LOANS: 'MANAGE_LOANS',
  MANAGE_EQUIPMENTS: 'MANAGE_EQUIPMENTS',
};
