const ADMIN_ROLE = 'Administrateur';
const REGISSEUR_GENERAL_ROLE = 'Regisseur General';
const REGISSEUR_LUMIERE_ROLE = 'Regisseur Lumiere';
const REGISSEUR_SON_ROLE = 'Regisseur Son';
const REGISSEUR_PLATEAU_ROLE = 'Regisseur Plateau';
const AUTRE_ROLE = 'Autre';

const ROLES = [
  ADMIN_ROLE,
  REGISSEUR_SON_ROLE,
  REGISSEUR_LUMIERE_ROLE,
  REGISSEUR_PLATEAU_ROLE,
  REGISSEUR_GENERAL_ROLE,
  AUTRE_ROLE,
];

module.exports = ROLES;
module.exports.ADMIN_ROLE = ADMIN_ROLE;
module.exports.REGISSEUR_GENERAL_ROLE = REGISSEUR_GENERAL_ROLE;
module.exports.REGISSEUR_LUMIERE_ROLE = REGISSEUR_LUMIERE_ROLE;
module.exports.REGISSEUR_SON_ROLE = REGISSEUR_SON_ROLE;
module.exports.REGISSEUR_PLATEAU_ROLE = REGISSEUR_PLATEAU_ROLE;
module.exports.AUTRE_ROLE = AUTRE_ROLE;
